import pytest

from scripts.feed_discovery.sources._base import SourceProtocol, ProbeResult
from scripts.feed_discovery.sources.youtube_top_subscribed import YouTubeTopSubscribedSource


@pytest.fixture
def source():
    return YouTubeTopSubscribedSource()


def test_implements_protocol(source):
    assert isinstance(source, SourceProtocol), \
        "YouTubeTopSubscribedSource does not implement SourceProtocol"


def test_source_name(source):
    assert source.name == "youtube_top_subscribed"


def test_has_search_callable(source):
    assert callable(source.search)


def test_has_probe_callable(source):
    assert callable(source.probe)


def test_enabled_when_data_file_exists(source):
    """Source should be enabled when the Wikipedia JSON exists."""
    # The data file should exist in the repo (generated by wikipedia scraper)
    # If it doesn't, the source is still valid but just returns empty
    assert isinstance(source.enabled, bool)


def test_loads_channels(source):
    """Channels should be loaded if data file exists."""
    if source.enabled:
        assert len(source._channels) > 0
        assert len(source._by_lang) > 0


def test_lang_mapping_built(source):
    """Language-to-country mapping should be built if countries.json exists."""
    if source.enabled:
        assert isinstance(source._lang_to_countries, dict)
        # At minimum we expect some common mappings
        if source._lang_to_countries:
            assert "en" in source._lang_to_countries or len(source._lang_to_countries) > 0


def test_country_to_langs(source):
    """_country_to_langs should return languages for known countries."""
    # Brazil → pt
    langs = source._country_to_langs("brazil")
    assert isinstance(langs, list)
    if source._lang_to_countries:
        assert "pt" in langs


@pytest.mark.asyncio
async def test_search_returns_candidates(source):
    """search() should return Candidate objects."""
    import aiohttp
    from scripts.feed_discovery.profiles._schema import CountryProfile, SourceConfig

    profile = CountryProfile(country="brazil", languages=["pt", "en"])
    config = SourceConfig(priority=7, timeout=5, max_results=10)

    async with aiohttp.ClientSession() as session:
        results = await source.search("", profile, config, session)
        assert isinstance(results, list)
        # If data exists and has pt/en channels, should get results
        if source.enabled and source._by_lang.get("pt") or source._by_lang.get("en"):
            assert len(results) > 0
            for c in results:
                assert c.category == "YouTube"
                assert c.url.startswith("https://www.youtube.com/feeds/videos.xml")


@pytest.mark.asyncio
async def test_probe_returns_probe_result(source):
    """probe() should return a ProbeResult."""
    import aiohttp
    from scripts.feed_discovery.profiles._schema import CountryProfile, SourceConfig

    profile = CountryProfile(country="br")
    config = SourceConfig(priority=7)

    async with aiohttp.ClientSession() as session:
        result = await source.probe(profile, config, session)
        assert isinstance(result, ProbeResult)
        assert result.source_name == "youtube_top_subscribed"
