# scripts/feed_discovery/sources/youtube_socialblade.py

from __future__ import annotations

import json
import time
from pathlib import Path

from ..models import Candidate
from ..profiles._schema import CountryProfile, SourceConfig
from ._base import ProbeResult


class YouTubeSocialBladeSource:
    """Social Blade public top-50 YouTube channels by country.

    Scraped from socialblade.com/youtube/top/country/{iso2} and cached
    as a JSON file. Contains top 50 channels for ALL 101 Feedmine countries
    with verified channel IDs and RSS feed URLs.

    Data generated by: scripts/socialblade_scraper.py
    Zero API calls at runtime — purely local data lookup.

    Data quality: Social Blade is the industry-standard YouTube analytics
    site. Rankings are based on subscriber counts updated regularly.
    """

    name = "youtube_socialblade"
    DATA_PATH = (
        Path(__file__).resolve().parents[1]
        / "data"
        / "youtube_channels_socialblade.json"
    )

    def __init__(self):
        self._by_country: dict[str, list[dict]] = {}
        self._channels: list[dict] = []
        self.enabled = self.DATA_PATH.exists()
        if self.enabled:
            self._load_data()

    def _load_data(self):
        """Load the Social Blade scraped JSON."""
        try:
            data = json.loads(self.DATA_PATH.read_text(encoding="utf-8"))
            self._by_country = data.get("by_country", {})
            self._channels = data.get("channels", [])
        except Exception:
            self._by_country = {}
            self._channels = []

    async def search(
        self,
        query: str,
        profile: CountryProfile,
        config: SourceConfig,
        session,
    ) -> list[Candidate]:
        """Return top YouTube channels for the profile's country from Social Blade.

        The query parameter is ignored — channels are matched by country slug.
        """
        if not self.enabled:
            return []

        country_slug = (profile.country or "").lower()
        candidates: list[Candidate] = []
        seen: set[str] = set()

        # Direct country match
        channels = self._by_country.get(country_slug, [])

        # Fallback: search flat channel list for country mention
        if not channels:
            for ch in self._channels:
                countries = ch.get("countries", [])
                if country_slug in countries:
                    channels.append(ch)

        for ch in channels:
            cid = ch.get("channel_id", "")
            if not cid or cid in seen:
                continue
            seen.add(cid)

            candidates.append(Candidate(
                url=ch.get("feed_url", ""),
                category="YouTube",
                title=ch.get("channel_name", ""),
                genre="",
                national=True,
                national_reason=f"socialblade:{country_slug}",
            ))

        return candidates[:config.max_results]

    async def probe(
        self,
        profile: CountryProfile,
        config: SourceConfig,
        session,
    ) -> ProbeResult:
        """Check if this source has channels for the profile's country."""
        if not self.enabled:
            return ProbeResult(
                source_name="youtube_socialblade",
                success=False,
                result_count=0,
                latency_ms=0,
                error="disabled: data file not found",
            )

        t0 = time.monotonic()
        try:
            results = await self.search("", profile, config, session)
            elapsed = (time.monotonic() - t0) * 1000
            return ProbeResult(
                source_name="youtube_socialblade",
                success=len(results) > 0,
                result_count=len(results),
                latency_ms=elapsed,
            )
        except Exception as e:
            elapsed = (time.monotonic() - t0) * 1000
            return ProbeResult(
                source_name="youtube_socialblade",
                success=False,
                result_count=0,
                latency_ms=elapsed,
                error=str(e)[:200],
            )
